# Generated by Django 2.1.2 on 2018-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181020_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], default='Customer', max_length=20),
        ),
    ]
