# Generated by Django 2.1.2 on 2018-10-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181020_1620'),
        ('missions', '0002_auto_20181020_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
