# Generated by Django 2.1.2 on 2018-10-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_auto_20181020_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='missions.Mission'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.User'),
        ),
    ]
