# Generated by Django 2.1.2 on 2018-10-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181020_1620'),
        ('missions', '0004_auto_20181020_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='finished_by_customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='finished_by_worker',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_missions', to='users.User'),
        ),
        migrations.AddField(
            model_name='mission',
            name='worker_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_missions', to='users.User'),
        ),
    ]
